name: Check Docker Version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - run: "bundle install"
    - run: "bundle exec rake"

    - name: Login to Docker Hub
      run: script/release-workflow/docker-login.sh
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t pactfoundation/pact-broker:latest .

    - name: Check Docker Version
      run: docker --version
    - name: Install Docker 19
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update
        sudo apt-cache madison docker-ce
        sudo apt-get install docker-ce=${DOCKER_VERSION} docker-ce-cli=${DOCKER_VERSION} containerd.io
      env:
        DOCKER_VERSION: 5:19.03.9~3-0~ubuntu-focal
    - name: Check Docker Version
      run: |-
        docker --version
        docker-compose --version

    - name: Integration tests
      run: script/test.sh
